trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: self
variables:
- name: dockerRegistryServiceConnection
  value: '0999e684-f448-4647-99b1-29dcc3fcd3e1'
- name: imageRepository
  value: 'abenzbackend'
- name: containerRegistry
  value: 'abenzbackendregistery.azurecr.io'
- name: dockerfilePath
  value: 'Dockerfile'
- name: tag
  value: 'latest'
- name: vmImageName
  value: 'ubuntu-latest'
stages:
- stage: Build
  displayName: Build Java app and push Docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Maven@4
      displayName: Maven Build, Test, and Package
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: Copy JAR files to artifact staging directory
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Publish JAR Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: Docker@2
      displayName: Build and Push Docker Image to Azure Container Registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(dockerfilePath)'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

